---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flappy
  namespace: www-public
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flappy
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flappy
    spec:
      containers:
      - image: aaraoz/me-flappi-app:main
        imagePullPolicy: Always
        name: flappy
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 56Mi
            cpu: 100m
          limits:
            memory: 64Mi
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: flappy
  namespace: www-public
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external-nginx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flappy
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flappy
  namespace: www-public
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: external-nginx
  rules:
    - http:
        paths:
        - path: /flappy
          pathType: Prefix
          backend:
            service:
              name: flappy
              port:
                number: 80
